Feature: Download search results. 
  
  As a user
  So that I can download search results
  I want to download search results
  
Background: Users in database
  
Given the following users exist:
    | name   | email            | password | password_confirmation | admin |
    | 666    | 666@gmail.com    | foobar   | foobar                | true  |
    | flyer1 | flyer1@gmail.com | foobar   | foobar                | true  |
    | 444    | 444@gmail.com    | foobar1  | foobar1               | false |

Given I am on the "login page"             
    And I fill in "Email" with "444@gmail.com" 
    And I fill in "Password" with "foobar1"     
    And I press "Log in"
    Then I am on the profile page
    And I should see "Profile"
    
Scenario: Search ArrayExpress page and export results
  Given I am on the profile page
  And I follow "Search Datasets"
  Then I should be on the SearchAll page
  And I should see "Search Datasets"
  Then I fill in "Search by Keyword" with "tuberculosis"
  And I check "Array Express"
  
  And I press "Search database"
  When I follow "Download"
  Then the downloaded file content should be:
    """
   Accession,GSE_ID,Name,Type,Organism,Release_Date,Assays,Relevance,Reason
E-MTAB-5287,ERP020415,Dual RNA-seq of M. tuberculosis H37Rv infecting macrophage-like THP-1 cells during 48h,RNA-seq of coding RNA,Homo sapiens,2017-08-01,84,unchecked,""
E-MTAB-5218,"","4-week mouse comparative study on effect of neutralizing IL-17A, IL-17F and TNFa antibodies",transcription profiling by array,Mus musculus,2016-12-02,75,unchecked,""
E-BUGS-155,"",Experiment to determine the effect of deleting the Rv1675c gene on the transcriptome of Mycobacterium tuberculosis,transcription profiling by array,Mycobacterium tuberculosis,2016-11-15,12,unchecked,""
E-BUGS-142,"",Non-Replicating Mycobacterium tuberculosis Elicits a Reduced Infectivity Profile with Corresponding Modifications to the Cell Wall and Extracellular Matrix,transcription profiling by array,Mycobacterium tuberculosis,2016-11-14,38,unchecked,""
E-MTAB-4257,"",Blood transcriptomic diagnosis of active tuberculosis and discrimination from other febrile illnesses,transcription profiling by array,Homo sapiens,2016-10-28,114,unchecked,""
E-MTAB-3872,"","Fat, lazy and indifferent - profiling persistent drug-tolerant tubercule bacilli from patient sputa during treatment predicts drug efficacy",transcription profiling by array,Mycobacterium tuberculosis H37Rv,2016-04-12,56,unchecked,""
E-MTAB-4093,"",The effect of growth rate on pyrazinamide activity in Mycobacterium tuberculosis; insights for early bactericidal activity,transcription profiling by array,Mycobacterium tuberculosis H37Rv,2016-03-25,30,unchecked,""
E-MTAB-3260,"",Whole blood transcriptional profiling of healthy volunteers and patients with active tuberculosis,transcription profiling by array,Homo sapiens,2016-02-09,31,unchecked,""
E-MTAB-3254,"",Molecular profiling of the tuberculin skin test in patients with active tuberculosis with and without HIV-1 co-infection,transcription profiling by array,Homo sapiens,2016-02-09,27,unchecked,""
E-MTAB-4099,"","Transcritpome analysis of Mycobacterium tuberculosis (Mtb) mutants deficient in ergothioneine, or mycothiol production",transcription profiling by array,Mycobacterium tuberculosis CDC1551,2016-01-27,1,unchecked,""
E-MTAB-2547,"",Transcriptional profiling of endobronchial ultrasound guided lymph node samples to aid diagnosis of mediastinal lymphadenopathy,transcription profiling by array,Homo sapiens,2016-01-06,47,unchecked,""
E-ERAD-409,ERP010905,Mycobacterium transcription survey,RNA-seq of coding RNA,Mycobacterium tuberculosis,2015-11-17,76,unchecked,""
E-MTAB-3192,ERP009094,Genome-wide maps of H3K4me1 in Mycobacterium tuberculosis H37Rv-infected macrophages,ChIP-seq,Homo sapiens,2015-10-15,14,unchecked,""
E-MTAB-3732,"",A comprehensive human expression map,transcription profiling by array,Homo sapiens,2015-07-23,1,unchecked,""
E-ERAD-355,ERP009144,Sequence analysis of Mycobacterium tuberculosis,RNA-seq of coding RNA,Mycobacterium tuberculosis,2015-06-23,98,unchecked,""
E-BUGS-151,"","Transcription profiling by tiling array of Potassium availability triggers Mycobacterium tuberculosis transition to, and resuscitation from, non-culturable (dormant) states",transcription profiling by array,Mycobacterium tuberculosis,2015-02-25,120,unchecked,""
E-TABM-1163,"",Transcription profiling by array of human monocyte derived macrophage infected with HIV1 with or without M. tuberculosis or S. pneumoniae stimulation,transcription profiling by array,Homo sapiens,2015-01-31,35,unchecked,""
E-MTAB-3252,ERP009333,"Transcription and translation of the rpsJ, rplN and rRNA operons of the tubercle bacillus",RNA-seq of coding RNA,Mycobacterium tuberculosis H37Rv,2015-01-23,1,unchecked,""
E-MTAB-3142,"",Gene expression profiling of Mycobacterium tuberculosis strain CDC1551 treated with experimental compounds,transcription profiling by array,Mycobacterium tuberculosis CDC1551,2014-12-13,18,unchecked,""
E-MTAB-2492,ERP005649,ChIP-seq of Mycobacterium tuberculosis with anti-GlnR antibody to study the role of the GlnR regulon in a nitrogen stress environment,ChIP-seq,Mycobacterium tuberculosis,2014-12-01,4,unchecked,""
E-MTAB-2390,ERP005267,Genomic mapping of cAMP receptor protein binding in relation to transcriptional start sites in Mycobacterium tuberculosis,ChIP-seq,Mycobacterium tuberculosis,2014-06-24,15,unchecked,""
E-BUGS-123,"",Transcription profiling by tiling array of Antimicrobial Treatment Improves Mycobacterial Survival in Non-Permissive Growth Conditions,transcription profiling by array,Mycobacterium bovis,2014-02-28,78,unchecked,""
E-MTAB-1616,ERP002485,RNA-seq of coding RNA of starved and exponentially grown M. tuberculosis cultures to investigate genome-wide transcriptional start sites,RNA-seq of coding RNA,Mycobacterium tuberculosis,2013-11-22,12,unchecked,""
E-BUGS-146,"",Transcription profiling by array of overexpression of the Rv0805 phosphodiesterase elicits a cAMP-independent transcriptional response,transcription profiling by array,Mycobacterium tuberculosis,2013-11-02,6,unchecked,""
E-MTAB-1446,ERP002122,RNA-seq of M. tuberculosis to investigate genotype-phenotype diversity amongst clinical isolates,RNA-seq of coding RNA,Mycobacterium tuberculosis,2013-09-19,13,unchecked,""
E-MTAB-1667,ERP002631,RNA-seq of coding RNA from Mycobacterium tuberculosis H37Rv overexpressing HigB compared to the empty vector control strain to investigate the role of the HigB toxin,RNA-seq of coding RNA,Mycobacterium tuberculosis,2013-09-16,2,unchecked,""
E-MEXP-3805,"",Transcription profiling by array of human monocyte-derived macrophages infected with Mycobacterium tuberculosis (H37Rv strain),transcription profiling by array,Homo sapiens,2013-06-01,12,unchecked,""
E-BUGS-135,"",Transcription profiling by array of adenylylation of mycobacterial Glnk (PII) protein induced by nitrogen limitation,transcription profiling by array,Mycobacterium tuberculosis,2013-05-10,6,unchecked,""
E-BUGS-134,"",Transcription profiling by array of longitudinal clinical isolates of Mycobacterium tuberculosis exhibiting rapid accumulation of drug resistance,transcription profiling by array,Mycobacterium tuberculosis,2013-04-24,8,unchecked,""
E-BUGS-139,"",Transcription profiling by array of Rifampicin-induced transcriptome response in rifampicin-resistant Mycobacterium tuberculosis,transcription profiling by array,Mycobacterium tuberculosis,2013-04-21,48,unchecked,""
E-MTAB-1374,"",Transcription profiling by array of Mycobacterium tuberculosis CDC1551 treated with 0.25M NaCl vs untreated controls,transcription profiling by array,Mycobacterium tuberculosis,2013-04-05,5,unchecked,""
E-MEXP-3589,"",Transcription profiling by array of human blood samples taken from patients with critical Chronic Obstructive Pulmonary Disease (COPD),transcription profiling by array,Homo sapiens,2013-03-12,32,unchecked,""
E-TABM-1157,"",Transcriptional profiling of in vivo immune responses to mycobacteria using the tuberculin skin test,transcription profiling by array,Homo sapiens,2012-05-13,33,unchecked,""
E-BUGS-122,"",Transcription profiling by array of Mycobacterium tuberculosis grown in the presence of ZnSO4,transcription profiling by array,Mycobacterium tuberculosis,2012-01-27,6,unchecked,""
E-TABM-1170,"",Modulation of transcriptional and inflammatory responses in murine macrophages by the Mycobacterium tuberculosis mammalian cell entry (Mce) 1 complex,transcription profiling by array,Mus musculus,2011-10-05,39,unchecked,""
E-MEXP-3521,"",Transcription profiling by array of human dendritic cells and macrophages infected with Mycobacterium tuberculosis,transcription profiling by array,Homo sapiens,2011-09-28,72,unchecked,""
E-BUGS-112,"","Methionine Sulfoximine Resistance in Mycobacterium tuberculosis Is Due to a Single Nucleotide Deletion Resulting in Increased Expression of the Major Glutamine Synthetase, GlnA1",transcription profiling by array,Mycobacterium tuberculosis,2011-09-06,108,unchecked,""
E-MTAB-427,"",Mouse-Monkey Time-series,transcription profiling by array,Macaca_fascicularis,2011-08-02,213,unchecked,""
E-MEXP-2962,"",IRF8 REGULATES EXPRESSION OF ANTIGEN PROCESSING AND PRESENTATION PATHWAYS IN MYELOID CELLS,transcription profiling by array,Mus musculus,2011-04-27,24,unchecked,""
E-BUGS-111,"",SigG does not control gene expression in response to DNA damage in Mycobacterium tuberculosis H37Rv,transcription profiling by array,Mycobacterium tuberculosis,2011-04-15,58,unchecked,""
E-BUGS-104,"",Examining the basis of isoniazid tolerance in nonreplicating Mycobacterium tuberculosis using transcriptional profiling,transcription profiling by array,Mycobacterium tuberculosis,2011-01-17,72,unchecked,""
E-TABM-852,"",Transcription profiling of diabetic vs non-diabetic human blood cells infected with Burkholderia pseudomallei,transcription profiling by array,Homo sapiens,2010-12-31,1,unchecked,""
E-BUGS-93,"",Transcription profiling by array of Mycobacterium bovis and Mycobacterium tuberculosis overexpressing overexpressing BCG3145 and Rv3124,transcription profiling by array,Mycobacterium bovis,2010-10-11,92,unchecked,""
E-BUGS-96,"",Transcription profiling by array of Mycobacterium tuberculosis clp gene regulator (ClgR) mutants,transcription profiling by array,Mycobacterium tuberculosis,2010-10-08,12,unchecked,""
E-BUGS-86,"",Transcription profiling by array of Mycobacterium tuberculosis virulent and attenuated strains infecting macrophages,transcription profiling by array,Mycobacterium tuberculosis,2010-08-16,52,unchecked,""
E-BUGS-107,"",Transcription profiling by array of Mycobacterium tuberculosis to analyse the regulatory role of the HigA antitoxin,transcription profiling by array,Mycobacterium tuberculosis,2010-07-16,48,unchecked,""
E-MEXP-2773,"",Transcription profiling by array of M. tuberculosis H37Rv wildtype and ctpV knockout exposed to copper,transcription profiling by array,Mycobacterium tuberculosis,2010-06-26,4,unchecked,""
E-MTAB-90,"",Transcription profiling of mouse IFNg-primed C57BL/6 and C3H.BL6-sst1 bone-marrow macrophages infected with mycobacterium tuberculosis,transcription profiling by array,Mus musculus,2010-01-07,24,unchecked,""
E-BUGS-91,"",Transcription profiling of Mycobacterium tuberculosis using a transposon mutagenesis approach to elucidate pe/ppe regulation,transcription profiling by array,Mycobacterium tuberculosis,2009-08-18,12,unchecked,""
E-MEXP-2202,"",Transcription profiling of Mycobacterium tuberculosis H37Rv wild type and deletion mutants for mce3R gene to investigate the expression of a regulon involved in lipid metabolism,transcription profiling by array,Mycobacterium tuberculosis,2009-06-17,16,unchecked,""
E-BUGS-83,"",Transcription profiling of Mycobacterium bovis to determine genetic requirements for fast and slow growth in Mycobacteria,transcription profiling by array,Mycobacterium bovis,2009-04-28,70,unchecked,""
E-BUGS-80,"",Transcription profiling of Mycobacterium tuberculosis treated with benzothiazinones which kill M. tuberculosis by blocking arabinan synthesis,transcription profiling by array,Mycobacterium tuberculosis,2009-03-19,24,unchecked,""
E-BUGS-54,"",Transcription profiling of Mycobacterium tuberculosis - a bayesian change point model for differential gene expression patterns of the DosR regulon,transcription profiling by array,Mycobacterium tuberculosis,2009-03-19,54,unchecked,""
E-MEXP-1942,"",Transcription profiling of mouse lung from C57BL6 and DBA2 parental strains and D2.B6-Chr7 and D2.B6-Chr19 congenic mice following aerosol infection with Mycobacterium tuberculosis for 30 and 70 days,transcription profiling by array,Mus musculus,2009-02-20,36,unchecked,""
E-BUGS-64,"",Transcription profiling of Mycobacterium bovis AN5 tuberculin production strain,transcription profiling by array,Staphylococcus aureus,2009-01-16,46,unchecked,""
E-MEXP-1899,"",Transcription profiling by array of lungs from mice infected with tuberculosis,transcription profiling by array,Mus musculus,2008-12-17,9,unchecked,""
E-BUGS-56,"",Transcription profiling of C. difficile following antibiotic stress,transcription profiling by array,Clostridium difficile,2008-11-18,40,unchecked,""
E-MEXP-944,"",Transcription profiling of Mycobacterium tuberculosis infected mice treated or non-treated with DNA-HSP65 vaccine treatment,transcription profiling by array,Mus musculus,2008-11-01,12,unchecked,""
E-BUGS-60,"",Quantification of global transcription patterns in prokaryotes using spotted microarrays,transcription profiling by array,Mycobacterium bovis,2008-09-30,114,unchecked,""
E-BUGS-66,"",Comparative genomic hybridization of Beijing and non-Beijing Myocobacterium tuberculosis isolates from Myanmar,transcription profiling by array,Mycobacterium tuberculosis,2008-09-26,44,unchecked,""
E-BUGS-63,"",Transcription profiling of Mycobacterium tuberculosis after treatment with ciprofloxacin to investigate the SOS DNA repair response,transcription profiling by array,Mycobacterium tuberculosis,2008-09-26,48,unchecked,""
E-BUGS-52,"",Transcription profiling of Mycobacterium tuberculosis grown in vitro and obtained from sputum to investigate the effect of whether they contain lipid bodies,transcription profiling by array,Mycobacterium tuberculosis,2008-04-02,68,unchecked,""
E-BUGS-61,"","Transcription profiling of Mycobacterium tuberculosis wild type and BCG strains after knock out of the global transcriptional regulator, CRP",transcription profiling by array,Mycobacterium tuberculosis,2008-03-12,12,unchecked,""
E-BUGS-42,"",Microarray analysis of defined Mycobacterium tuberculosis populations using RNA amplification strategies,transcription profiling by array,Mycobacterium tuberculosis,2008-03-12,248,unchecked,""
E-BUGS-59,"",Characterisation of two in vivo expressed methyltransferases of the Mycobacterium tuberculosis complex: antigenicity and genetic regulation,transcription profiling by array,Mycobacterium tuberculosis,2008-01-09,36,unchecked,""
E-BUGS-58,"",Transcription profiling of Mycobacterium tuberculosis infected human dendritic cells and macrophages and M. tuberculosis grown aerobically to investigate host-pathogen cross-talk,transcription profiling by array,Mycobacterium tuberculosis,2008-01-04,88,unchecked,""
E-MEXP-404,"",Transcription profiling of Arabidopsis roots from transgenic arabidopsis lines expressing the p25 protein of beet necrotic yellow vein virus,transcription profiling by array,Arabidopsis thaliana,2007-12-08,12,unchecked,""
E-MEXP-857,"","Transcription profiling of brain samples from human control and schizophrenia patients who were treated with either typical, atypical or no antipsychotic medication",transcription profiling by array,Homo sapiens,2007-12-06,16,unchecked,""
E-BUGS-37,"",Transcription profiling of Mycobacterium bovis and Mycobacterium tuberculosis to identify key gene expression differences,transcription profiling by array,Mycobacterium bovis,2007-10-11,236,unchecked,""
E-MARS-7,"",Transcription profiling of human mononuclear cells after treatment with suppressor carbohydrates produced by CD8+ gd T cells in response to Mycobacterium tuberculosis,transcription profiling by array,Homo sapiens,2007-10-06,10,unchecked,""
E-SMDB-4099,"",Transcription profiling of Mycobacterium tuberculosis wild type and Rv3133c/DosR mutants grown in hypoxic conditions,transcription profiling by array,Mycobacterium tuberculosis,2007-09-29,12,unchecked,""
E-SMDB-4062,"",Transcription profiling of Mycobacterium tuberculosis treated with nitric oxide to investigate the effect on latency,transcription profiling by array,Mycobacterium tuberculosis,2007-09-29,131,unchecked,""
E-BUGS-49,"",Mycobacterial cells have dual nickel-cobalt sensors: sequence-relationships and metal-sites of metal-responsive repressors are not congruent,transcription profiling by array,Mycobacterium tuberculosis,2007-09-17,51,unchecked,""
E-TABM-317,"","Transcription profiling of Mycobacterium tuberculosis wild type, ideR mutant and ideR complemented mutants strains grown in iron-sufficient or iron-deficient media",transcription profiling by array,Mycobacterium tuberculosis,2007-09-12,18,unchecked,""
E-TABM-316,"",Transcription profiling of Mycobacterium tuberculosis wild type and sigH mutant strains after exposure to the thiol-specific oxidizing agent diamide,transcription profiling by array,Mycobacterium tuberculosis,2007-09-12,15,unchecked,""
E-TABM-313,"",Transcription profiling of Mycobacterium tuberculosis wild type and sigE mutant strains after exposure to stress induced by SDS,,Mycobacterium tuberculosis,2007-09-12,15,unchecked,""
E-TABM-312,"",Transcription profiling of Mycobacterium tuberculosis grown at reduced oxygen tension to identify regulators of the hypoxic response,transcription profiling by array,Mycobacterium tuberculosis,2007-09-12,6,unchecked,""
E-BUGS-44,"",Comparative genomic hybridization of the dominant strains of Mycobacterium tuberculosis in a UK South Asian community,transcription profiling by array,Mycobacterium tuberculosis,2007-09-06,40,unchecked,""
E-SMDB-4101,"",Transcription profiling of Mycobacterium tuberculosis to study stationary phase and dormancy gene expression,transcription profiling by array,Mycobacterium tuberculosis,2007-08-24,55,unchecked,""
E-BUGS-35,"",Transcription profiling of Mycobacterium tuberculosis grown under iron-limitation in continuous culture,transcription profiling by array,Mycobacterium tuberculosis,2007-06-25,48,unchecked,""
E-BUGS-43,"","Transcription profiling of five strains of Mycobacterium bovis in order to understand the evolution, attenuation and variable protective efficacy of BCG vaccines",transcription profiling by array,Mycobacterium bovis,2007-03-20,110,unchecked,""
E-BUGS-2,"",Dissection of the heat-shock response in Mycobacterium tuberculosis using mutants and microarrays,transcription profiling by array,Mycobacterium tuberculosis,2007-03-07,27,unchecked,""
E-BUGS-31,"",Transcription profiling of Mycobacterium bovis with pYUB412 and pRD1-2F9 genes knocked-in to investigate the ESX-1 secretion system,transcription profiling by array,Mycobacterium bovis,2007-01-30,8,unchecked,""
E-BUGS-21,"",Transcription profiling of and Rv3676 deletion strain of Mycobacterium tuberculosis vs wild type,transcription profiling by array,Mycobacterium tuberculosis,2007-01-30,14,unchecked,""
E-MEXP-552,"",Transcription profiling of Mycobacterium tuberculosis H37Rv and the isogenic mprA::Kmr mutant,transcription profiling by array,Mycobacterium tuberculosis,2006-03-01,17,unchecked,""
E-SMDB-2867,"",Transcription profiling of a complex phenotype: cord formation in Mycobacterium tuberculosis,transcription profiling by array,Mycobacterium tuberculosis,2005-11-03,40,unchecked,""
E-SMDB-2885,"",Transcription profiling of Mycobacterium tuberculosis 12 clinical isolates,transcription profiling by array,Mycobacterium tuberculosis,2005-08-23,48,unchecked,""
E-MEXP-405,"",Transcription profiling of zebrafish at the late stage of chronic tuberculosis due to Mycobacterium marinum infection,transcription profiling by array,Danio rerio,2005-08-17,4,unchecked,""

    """
  